export const features = {
  WiFi: false,
  WaterFountain: false,
  PowerSockets: false,
  Noisy: false,
  Food: false,
  Beverages: false,
  Toilets: false,
  WheelchairAccess: false,
  DiasabledToilets: false,
  GenderNeutralToilets: false,
  FreeParking: false,
  PaidParking: false,
  PetFriendly: false,
  Vegetarian: false,
  Vegan: false,
  OutdoorSeating: false,
  PhoneSignal: false,
  NaturalLight: false,
};
